# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f24bcdbaa1e8d39aa9abfd382dfefa81ebae0326e752625ab5b9f975d20eed3a5a15f8cc4f669b20365e23db05c1485ebac3fb046c6235c1e41dc50f501e8f17

test:
  secret_key_base: dcbe271ed3ddc4c4145ce6a10ad31cce5ecc79549dbf4a8fb768c112ef3d5531e0425428bda05353a8c599a3df2099b86e9e8da9bc00cbbef5a859c45299d7e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
